server:
  port: 8888
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /r/**
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: dkagh
mybatis:
  mapper-locations: classpath:/mappers/**/*.xml

logging:
  level:
    com:
      leftb:
        bootexer:
          dao: trace
